#!/bin/sh
# Copyright (c) 2012 The Native Client Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#
# This script builds all ports in all possible configurations.
# If you want to be sure your change won't break anythign this is
# a good place to start.

cp ./pnacl/Release/recorder.pexe ../addon/_platform_specific/
cp ./pnacl/Release/recorder_unstripped.bc ../addon/_platform_specific/
cp ./pnacl/Release/recorder_unstripped.pexe ../addon/_platform_specific/
